### ISSUE TITLE
[Help] Acceptance test on Ember-cli 0.2.7, Ember 1.13 and Ember-intl 2.0.0-beta.5

### ISSUE THREAD

**Issue by ziggurat** [yahoo/ember-intl#140]
I am not able to succesfully create an acceptance test for a project using:

* ember-cli 0.2.7
* ember 1.13 
* ember-intl 2.0.0-beta.5

the most basic auto generated tests gives me:

    TypeError: 'undefined' is not a function (evaluating 'service.createLocale.bind(service, instance)')

Any ideas?

**Comment by jasonmit** [comment]
Can you isolate the issue and push your sample project github?

**Comment by al3x-edge** [comment]
What is your PhantomJS version as well?

**Comment by ziggurat** [comment]
Sorry for the delay, will try to have the sample project today. PhantomJS version is 1.9.

**Comment by ziggurat** [comment]
Ok, I uploaded a one route project here: https://github.com/ziggurat/acceptanceTestEmberIntl

There is a page with an ember-intl helper and an acceptance test.
The acceptance test fails and I got this error message:

    TypeError: 'undefined' is not a function (evaluating 'service.createLocale.bind(service, instance)')


Also (unrelated maybe) I can't manage to use this line from the sample test in the documentation as it says it can't find the module:

    import { registerIntl } from '../../../initializers/ember-intl';

Thanks in advance for your help and let me know if you need more information.

**Comment by jasonmit** [comment]
Thanks, I'll dip into this tonight :+1:

**Comment by jasonmit** [comment]
@ziggurat issue is fixed, I just need to validate everything still works on 1.10.  Should be merged tonight.

**Comment by ziggurat** [comment]
Amazing! Thanks, and keep up the excelent work!

**Comment by jasonmit** [comment]
Versioned now as 2.0.0-beta.6

Feel free to reopen if you see the same error.  I tested it on 1.10 and your branch and the issue should be fixed.

**Comment by ziggurat** [comment]
Thanks again!
